repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: git://github.com/gruntwork-io/pre-commit
    rev: v0.1.5
    hooks:
      - id: markdown-link-check
      - id: shellcheck
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
